# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('S3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S3.Path'),
        ),
    ]
